apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo-go-app-deployment
spec:
  selector:
    matchLabels:
      app: k8s-demo-go-app
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-demo-go-app
    spec:
      containers:
      - name: k8s-demo-go-app
        image: juggernaut/k8s-demo-go-app:v0.0.4
        ports:
        - containerPort: 8080

