name: Deploy

on:
  push:
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install kubectl
        run: curl -LO https://dl.k8s.io/release/v1.21.3/bin/linux/amd64/kubectl

      - name: Deploy to k8s cluster
        run: ./kubectl --kubeconfig <(echo "$KUBECONF_DATA" | base64 -d) get deployments
